dependencies {
    implementation project(':app')
    implementation project(':integration-api')
}

sourceSets {
    test {
        java.setSrcDirs([])
        resources.setSrcDirs([])
    }
}

test {
    enabled = false
}

testing {
    suites {
        integrationTest(JvmTestSuite) {
            useJUnitJupiter()

            dependencies {
                compileOnly 'org.projectlombok:lombok'
                annotationProcessor 'org.projectlombok:lombok'

                implementation project(':app')
                implementation project(':integration-api')
                implementation 'org.springframework.boot:spring-boot-starter-test'
                implementation 'org.springframework.boot:spring-boot-starter-web'
                implementation 'org.springframework.boot:spring-boot-test'
                implementation 'org.springframework.boot:spring-boot-restclient'
                implementation 'org.springframework.boot:spring-boot-resttestclient'
                implementation 'io.github.microcks:microcks-testcontainers'
            }

            sources {
                java {
                    srcDirs = ['src/test/java']
                }
                resources {
                    srcDirs = ['src/test/resources']
                }
            }
            configurations {
                integrationTestAnnotationProcessor.extendsFrom testAnnotationProcessor
                integrationTestImplementation.extendsFrom testImplementation
                integrationTestCompileOnly.extendsFrom testCompileOnly
            }
            targets.all {
                testTask.configure {
                    shouldRunAfter(test)
                    jvmArgs += [
                            "-javaagent:${configurations.mockitoAgent.asPath}",
                            "-Xshare:off"
                    ]
                }
            }
        }
    }
}